# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud_controller_future.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cloudfoundry.copilot.protos.MapRouteRequest" do
    optional :process, :message, 1, "cloudfoundry.copilot.protos.MapRouteRequest.Process"
    optional :route_guid, :string, 2
  end
  add_message "cloudfoundry.copilot.protos.MapRouteRequest.Process" do
    optional :guid, :string, 1
    optional :app_guid, :string, 2
  end
  add_message "cloudfoundry.copilot.protos.MapRouteResponse" do
  end
  add_message "cloudfoundry.copilot.protos.UnmapRouteRequest" do
    optional :process_guid, :string, 1
    optional :route_guid, :string, 2
  end
  add_message "cloudfoundry.copilot.protos.UnmapRouteResponse" do
  end
  add_message "cloudfoundry.copilot.protos.DeleteRouteRequest" do
    optional :guid, :string, 1
  end
  add_message "cloudfoundry.copilot.protos.DeleteRouteResponse" do
  end
  add_message "cloudfoundry.copilot.protos.UpsertRouteRequest" do
    optional :guid, :string, 1
    optional :host, :string, 2
    optional :path, :string, 3
  end
  add_message "cloudfoundry.copilot.protos.UpsertRouteResponse" do
  end
  add_message "cloudfoundry.copilot.protos.BulkSyncRequest" do
    repeated :routes, :message, 1, "cloudfoundry.copilot.protos.UpsertRouteRequest"
    repeated :route_mappings, :message, 2, "cloudfoundry.copilot.protos.MapRouteRequest"
  end
  add_message "cloudfoundry.copilot.protos.BulkSyncResponse" do
  end
end

module Cloudfoundry
  module Copilot
    module Protos
      MapRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.MapRouteRequest").msgclass
      MapRouteRequest::Process = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.MapRouteRequest.Process").msgclass
      MapRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.MapRouteResponse").msgclass
      UnmapRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.UnmapRouteRequest").msgclass
      UnmapRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.UnmapRouteResponse").msgclass
      DeleteRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.DeleteRouteRequest").msgclass
      DeleteRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.DeleteRouteResponse").msgclass
      UpsertRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.UpsertRouteRequest").msgclass
      UpsertRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.UpsertRouteResponse").msgclass
      BulkSyncRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.BulkSyncRequest").msgclass
      BulkSyncResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloudfoundry.copilot.protos.BulkSyncResponse").msgclass
    end
  end
end
