apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-service
  namespace: kube-system
  labels:
    k8s-app: nginx-ingress-controller-service
  annotations:
    prometheus.io/port: '10254'
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 10254
    protocol: TCP
  selector:
    k8s-app: nginx-ingress-controller
