apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bitesize-authz-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitesize-authz-webhook
  template:
    metadata:
      labels:
        app: bitesize-authz-webhook
    spec:
      containers:
        - name: bitesize-authz-webhook
          image: geribatai/bitesize-authz-webhook:0.0.7
          ports:
          - containerPort: 8080
            name: https
            protocol: TCP
          volumeMounts:
            - name: bitesize
              mountPath: /etc/bitesize
          env:
            - name: RULES_CONFIG
              value: /etc/bitesize/rules.hcl
            - name: HTTPS_ENABLED
              value: "true"
            - name: SSL_CERT
              value: /etc/bitesize/cert.pem
            - name: SSL_KEY
              value: /etc/bitesize/key.pem
      volumes:
        - name: bitesize
          secret:
            secretName: bitesize
---
apiVersion: v1
kind: Service
metadata:
  name: bitesize-authz-webhook-service
  labels:
    name: bitesize-authz-webhook-service
spec:
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app: bitesize-authz-webhook
  type: ClusterIP
