clusters:
  - name: bitesize-authz
    cluster:
      insecure-skip-tls-verify: true
      server: https://bitesize-authz-webhook-service:443
users:
  - name: user
    user:
      client-certificate: /etc/bitesize/cert.pem
      client-key: /etc/bitesize/key.pem
current-context: webhook
contexts:
- context:
    cluster: bitesize-authz
    user: user
  name: webhook
