// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/copilot/handlers"
)

type CAPIDiegoProcessAssociationsRepo struct {
	UpsertStub        func(capiDiegoProcessAssociation handlers.CAPIDiegoProcessAssociation)
	upsertMutex       sync.RWMutex
	upsertArgsForCall []struct {
		capiDiegoProcessAssociation handlers.CAPIDiegoProcessAssociation
	}
	DeleteStub        func(capiProcessGUID handlers.CAPIProcessGUID)
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		capiProcessGUID handlers.CAPIProcessGUID
	}
	ListStub        func() map[handlers.CAPIProcessGUID]handlers.DiegoProcessGUIDs
	listMutex       sync.RWMutex
	listArgsForCall []struct{}
	listReturns     struct {
		result1 map[handlers.CAPIProcessGUID]handlers.DiegoProcessGUIDs
	}
	listReturnsOnCall map[int]struct {
		result1 map[handlers.CAPIProcessGUID]handlers.DiegoProcessGUIDs
	}
	GetStub        func(capiProcessGUID handlers.CAPIProcessGUID) handlers.CAPIDiegoProcessAssociation
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		capiProcessGUID handlers.CAPIProcessGUID
	}
	getReturns struct {
		result1 handlers.CAPIDiegoProcessAssociation
	}
	getReturnsOnCall map[int]struct {
		result1 handlers.CAPIDiegoProcessAssociation
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CAPIDiegoProcessAssociationsRepo) Upsert(capiDiegoProcessAssociation handlers.CAPIDiegoProcessAssociation) {
	fake.upsertMutex.Lock()
	fake.upsertArgsForCall = append(fake.upsertArgsForCall, struct {
		capiDiegoProcessAssociation handlers.CAPIDiegoProcessAssociation
	}{capiDiegoProcessAssociation})
	fake.recordInvocation("Upsert", []interface{}{capiDiegoProcessAssociation})
	fake.upsertMutex.Unlock()
	if fake.UpsertStub != nil {
		fake.UpsertStub(capiDiegoProcessAssociation)
	}
}

func (fake *CAPIDiegoProcessAssociationsRepo) UpsertCallCount() int {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return len(fake.upsertArgsForCall)
}

func (fake *CAPIDiegoProcessAssociationsRepo) UpsertArgsForCall(i int) handlers.CAPIDiegoProcessAssociation {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return fake.upsertArgsForCall[i].capiDiegoProcessAssociation
}

func (fake *CAPIDiegoProcessAssociationsRepo) Delete(capiProcessGUID handlers.CAPIProcessGUID) {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		capiProcessGUID handlers.CAPIProcessGUID
	}{capiProcessGUID})
	fake.recordInvocation("Delete", []interface{}{capiProcessGUID})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		fake.DeleteStub(capiProcessGUID)
	}
}

func (fake *CAPIDiegoProcessAssociationsRepo) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *CAPIDiegoProcessAssociationsRepo) DeleteArgsForCall(i int) handlers.CAPIProcessGUID {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].capiProcessGUID
}

func (fake *CAPIDiegoProcessAssociationsRepo) List() map[handlers.CAPIProcessGUID]handlers.DiegoProcessGUIDs {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct{}{})
	fake.recordInvocation("List", []interface{}{})
	fake.listMutex.Unlock()
	if fake.ListStub != nil {
		return fake.ListStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.listReturns.result1
}

func (fake *CAPIDiegoProcessAssociationsRepo) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *CAPIDiegoProcessAssociationsRepo) ListReturns(result1 map[handlers.CAPIProcessGUID]handlers.DiegoProcessGUIDs) {
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 map[handlers.CAPIProcessGUID]handlers.DiegoProcessGUIDs
	}{result1}
}

func (fake *CAPIDiegoProcessAssociationsRepo) ListReturnsOnCall(i int, result1 map[handlers.CAPIProcessGUID]handlers.DiegoProcessGUIDs) {
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 map[handlers.CAPIProcessGUID]handlers.DiegoProcessGUIDs
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 map[handlers.CAPIProcessGUID]handlers.DiegoProcessGUIDs
	}{result1}
}

func (fake *CAPIDiegoProcessAssociationsRepo) Get(capiProcessGUID handlers.CAPIProcessGUID) handlers.CAPIDiegoProcessAssociation {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		capiProcessGUID handlers.CAPIProcessGUID
	}{capiProcessGUID})
	fake.recordInvocation("Get", []interface{}{capiProcessGUID})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(capiProcessGUID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getReturns.result1
}

func (fake *CAPIDiegoProcessAssociationsRepo) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *CAPIDiegoProcessAssociationsRepo) GetArgsForCall(i int) handlers.CAPIProcessGUID {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].capiProcessGUID
}

func (fake *CAPIDiegoProcessAssociationsRepo) GetReturns(result1 handlers.CAPIDiegoProcessAssociation) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 handlers.CAPIDiegoProcessAssociation
	}{result1}
}

func (fake *CAPIDiegoProcessAssociationsRepo) GetReturnsOnCall(i int, result1 handlers.CAPIDiegoProcessAssociation) {
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 handlers.CAPIDiegoProcessAssociation
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 handlers.CAPIDiegoProcessAssociation
	}{result1}
}

func (fake *CAPIDiegoProcessAssociationsRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CAPIDiegoProcessAssociationsRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
